config/routes.rb
Rails.application.routes.draw do
	devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'books#top'
  get "home/about" => 'books#about'
  resources :users, only: [:show, :index, :edit, :update] do
  	member do
  		get :followings, :followers
  	end
  end
  resources :books, only: [:new, :index, :create, :show, :edit, :destroy, :update ]
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user
	validates :title,
		presence: true
	validates :body,
		presence: true,
	  	length: { minimum: 1, maximum: 200 }

end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :user
	belongs_to :follow, class_name: 'User'


	validates :user_id, presence: true
	validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books,dependent: :destroy
  attachment :profile_image
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :user

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  validates :name,
	  uniqueness: { case_sensitive: :false },
	  length: { minimum: 2, maximum: 20 }
  validates :introduction,
	  uniqueness: { case_sensitive: :false },
	  length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	 before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end

  def after_sign_out_path_for(reosuce)
    flash[:notice] = 'Signed out successfully.'
    root_path
  end

  def after_sign_in_path_for(reosuce)
    flash[:notice] = 'Welcome! You have sign in successfully.'
  	user_path(resource)
  end

  def after_sign_up_path_for(reosuce)
    flash[:notice] = 'Welcome! You have signed up successfully.'
    user_path(resource)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!, only: [:index, :create, :show, :edit, :update, :destroy]

	def index
		@book = Book.new
		@books = Book.all
	end

	def create
		@book = Book.new(book_params)
		@book.user_id = current_user.id
		if @book.save
		   flash[:notice] = 'You have creatad book successfully.'
		   redirect_to book_path(@book.id)
		else
			@books = Book.all
			render :index
		end
	end

	def show
		@book = Book.new
		@books = Book.find(params[:id])
	end

	def edit
		@book = Book.find(params[:id])
		if @book.user == current_user
			render :edit
		else
			redirect_to books_path
		end
	end

	def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
		   flash[:notice] = 'You have updated book successfully.'
		   redirect_to book_path(@book.id)
		else
			render :edit
		end
	end

	def destroy
		@book = Book.find(params[:id])
		@book.destroy
		redirect_to books_path
	end

	private
    def book_params
		params.require(:book).permit(:title, :body)
	end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

	def create
		@user = User.find(params[:follow_id])
		following = current_user.follow(@user)
	end

	def destroy
		@user = User.find(params[:follow_id])
		following = current_user.unfollow(@user)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!


  def show
   @user = User.find(params[:id])
  	@book = Book.new
  	@books = @user.books
  end

  def index
  	@users = User.all
    @book = Book.new
  end

  def edit
  	@user = User.find(params[:id])
    if @user.id == current_user.id
      render :edit
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
  	@user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] ='You have updated user successfully.'
       redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def followings
    @user = User.find(params[:id])
    @users = @user.followings
    render 'followings'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'followers'
  end


  private
    def user_params
		params.require(:user).permit(:name, :introduction, :profile_image)
	 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/ralstionships_helper.rb
module RalstionshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
	<% if @book.errors.any? %>
		<p><%= @book.errors.count %>error prohibited this obj from being saved: </p>
		<ul>
			<% @book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>

	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h1>Editing Book</h1>
			<%= form_for(@book) do |f| %>
			<div class="field row">
				<label>Title</label>
				<%= f.text_field :title, class:"col-xs-12 book_title" %>
			</div>
			<div class="field row">
				<label>Opinion</label>
				<%= f.text_area :body, class:"col-xs-12 book_body" %>
			</div>
			<div class="actions row">
				<%= f.submit "Update Book" , class:"btn btn-primary col-xs-12" %>
			</div>
			<% end %>
			<%= link_to "Show", book_path(@book) %>|<%= link_to "Back", books_path %>
		</div>
	</div>
</div>

app/views/books/index.html.erb
<div class="container">
	<% if @book.errors.any? %>
		<p><%= @book.errors.count %>error prohibited this obj from being saved: </p>
		<ul>
			<% @book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>

	<div class="row">
		<div class="col-xs-3">
			<h2>User info</h2>
			<%= attachment_image_tag current_user, :profile_image, size: "100x100", format: 'jpeg', fallback: "no_image.jpg" %>
			<table class="table">
				<tbody>
					<tr></tr>
					<tr>
						<th><label>name</label></th>
						<td><%= current_user.name %></td>
					</tr>
					<tr>
						<th><label>introduction</label></th>
						<td><%= current_user.introduction %></td>
					</tr>
					<tr>
						<th><label>follows</label></th>
						<td><a href="<%= followings_user_path(current_user) %>"><%= current_user.followings.count %></a></td>
					</tr>
					<tr>
						<th><label>followers</label></th>
						<td><a href="<%= followers_user_path(current_user) %>"><%= current_user.followers.count %></a></td>
					</tr>
				</tbody>
			</table>
			<div class="row">
				<%= link_to "", edit_user_path(current_user) , class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_18935" %>
			</div>
			<h2>New book</h2>
			<%= form_for(@book) do |f| %>
				<div class="field row">
						<label>Title</label>
						<%= f.text_field :title, class:"col-xs-12 book_title" %>
				</div>
				<div class="field row">
						<label>Opinion</label>
						<%= f.text_area :body, class:"col-xs-12 book_body"%>
				</div>
				<div class="actions row">
					<%= f.submit "Create Book", class:"btn btn-primary col-xs-12" %>
				</div>
			<% end %>
		</div>

		<div class="col-xs-9">
			<h2>Books</h2>
			<table class="table table-hover table-inverse">
				<thead>
				  	<tr>
				  		<th></th><th>Title</th><th>Opinion</th>
				  	</tr>
			  	</thead>
			  	<tbody>
			  	<% @books.each do |book| %>
			  	<tr>
			  		<td><%= link_to user_path(book.user.id) do %><%= attachment_image_tag book.user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %><% end %></td>
			  		<td><%= link_to book_path(book.id) do %><%= book.title %><% end %></td>
			  		<td><%= book.body %></td>
			  	</tr>
			  	<% end %>
			</table>
	  	</div>
	</div>
</div>

app/views/books/show.html.erb
<div class ="container">

	<% if @book.errors.any? %>
		<p><%= @book.errors.count %>error prohibited this obj from being saved: </p>
		<ul>
			<% @book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>

	<% if flash[:notice] %>
		<div class="flash"><%= flash[:notice] %></div>
	<% end %>


	<div class="row">
		<div class="col-xs-3">
			<h2>User info</h2>
			<%= attachment_image_tag @books.user, :profile_image, size: "100x100", format: 'jpeg', fallback: "no_image.jpg" %>
			<table class="table">
				<tr></tr>
				<tr>
					<th><label>name</label></th>
					<th><p><%= @books.user.name %></p></th>
				</tr>
				<tr>
					<th><label>introduction</label></th>
					<th><p><%= @books.user.introduction %></p></th>
				</tr>
				<tr>
					<th><%= render 'relationships/follow_button', user: @books.user %></th>
				</tr>
			</table>
			<% if @books.user.id == current_user.id %>
				<%= link_to "", edit_user_path(@books.user), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_18898" %>
			<% end %>

			<div class="create">
				<h2>New book</h2>
				<%= form_for(@book) do |f| %>
					<div class="field row">
						<label>Title</label>
						<%= f.text_field :title, class:"col-xs-12 book_title" %>
					</div>
					<div class="field row">
						<label>Opinion</label>
						<%= f.text_area :body , class:"col-xs-12 book_body"%>
					</div>
					<div class="action row">
					<%= f.submit "Create Book", class:"btn btn-primary col-xs-12" %>
					</div>
				<% end %>
			</div>
		</div>

		<div class="col-xs-9">
			<h2>Book detail</h2>
			<table class="table table-hover table-inverse">
				<tbody>
				<tr>
					<td>
						<%= link_to user_path(@books.user) do %>
							<%= attachment_image_tag @books.user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %><br>
							<%= @books.user.name %>
						<% end %>
					</td>
					<td><%= @books.title %></td>
					<td><%= @books.body %></td>
					<td>
						<% if @books.user == current_user %>
							<%= link_to "Edit", edit_book_path %>
					</td>
					<td>
						<%= link_to "Destroy",  book_path(@books.id), method: :delete, data: {confirm: "本当に削除しますか？"} %>
						<% end %>
					</td>
				</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/books/top.html.erb
<div class="container">
	<% if flash[:notice] %>
		<div class="flash"><%= flash[:notice] %></div>
	<% end %>
	<div class="row">
		<div class="top-message col-md-offset-3 col-md-6">
			<h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong></span>  !!</h1>

			<p>In <span class="glyphicon glyphicon-book"><strong>Bookers</strong></span></p>
			<p>	you can share and exchange your opinions ,inpressions ,and emotions</p>
			<p>about various books!</p>
			<div class="btn-wrapper">
			<% if user_signed_in? %>
				<div class="row">
				<p><%= link_to "Log in", users_path(params[:id]), class:"btn btn-info col-xs-10 col-xs-offset-1 sign_in" %></p>
				<p><%= link_to "Sign up", users_path(params[:id]), class:"btn btn-success col-xs-10 col-xs-offset-1 sign_up" %></p>
			<% else %>
				<p><%= link_to "Log in", new_user_session_path, class:"btn btn-info col-xs-10 col-xs-offset-1 sign_in" %></p>
				<p><%= link_to "Sign up", new_user_registration_path, class:"btn btn-success col-xs-10 col-xs-offset-1 sign_up" %></p>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header class="navbar navbar-fixed-top navbar-inverse clearfix">
    <div class="container">
      <nav class="nav navbar-nav navbar-left">
        <span>Bookers</span>
      </nav>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li>
              <%= link_to ' Home', user_path(current_user.id), class:"glyphicon glyphicon-home home" %>
            </li>
            <li>
              <%= link_to ' Users', users_path, class:"glyphicon glyphicon-link users" %>
            </li>
            <li>
              <%= link_to ' Books', books_path,class:"glyphicon glyphicon-edit books" %>
            </li>
            <li>
              <%= link_to " logout", destroy_user_session_path, method: :delete, class:"glyphicon glyphicon-log-in logout" %>
            </li>

          <% else %>
            <li>
              <%= link_to " Home", root_path, class:"glyphicon glyphicon-home home" %></a>
            </li>
            <li>
              <%= link_to " About", home_about_path, class:"glyphicon glyphicon-link about" %>
            </li>
            <li>
              <%= link_to " sign up", new_user_registration_path, class:"glyphicon glyphicon-edit sign-up" %>
            </li>
            <li>
              <%= link_to " login", new_user_session_path, class:"glyphicon glyphicon-log-in login" %>
            </li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>

  <body>
    <div class="body cleafix">
      <%= yield %>
    </div>
  </body>

  <fotter>
    <div class="container">
      <div class="row">
        <div class="col-xs-3 col-xs-offset-9">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </fotter>
</html>

app/views/relationships/_follow_button.html.erb
<div id="relationships-<%= user.id %>">
<% unless current_user == user %>
	<% if current_user.following?(user) %>
		<%= form_for(current_user.relationships.find_by(follow_id: user.id), method: :delete, remote: true) do |f| %>
			<%= hidden_field_tag :follow_id, user.id %>
			<%= f.submit 'フォロー解除' , class:"btn btn-primary"%>
		<% end %>
	<% else %>
		<%= form_for(current_user.relationships.build, remote: true) do |f| %>
			<%= hidden_field_tag :follow_id, user.id %>
			<%= f.submit 'フォローする' , class:"btn btn-success"%>
		<% end %>
	<% end %>
<% end %>
</div>

app/views/relationships/create.js.erb
$( "#relationships-<%= @user.id %>").html("<%= j(render partial: 'relationships/follow_button', locals: { user: @user })%>");

app/views/relationships/destroy.js.erb
$( "#relationships-<%= @user.id %>").html("<%= j(render partial: 'relationships/follow_button', locals: { user: @user })%>");

app/views/users/edit.html.erb
<div class="container">

<div id="error">
	<% if @user.errors.any? %>
		<p><%= @user.errors.count %>error prohibited this obj from being saved: </p>
		<ul>
			<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>
</div>

<h2>User info</h2>
<%= form_for(@user) do |f| %>
	<div class="field">
		<label>Name</label>
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<label>Image</label>
        <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
        <%= f.attachment_field :profile_image, placeholder: "ファイルを選択", class: "user-edit-form" %>
    </div>
    <div class="field">
		<label>Introduction</label>
		<%= f.text_area :introduction %>
	</div>
	<div class="actions">
		<%= f.submit "Update User" %>
	</div>
<% end %>
</div>

app/views/users/followers.html.erb
<div class="container">
<h1>Follow Users</h1>

<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th></th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<% @user.followers.each do |user| %>
	<tbody>
		<tr>
			<td><%= attachment_image_tag user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %>
			<td><%= user.name %></td>
			<td>フォロー数:<%= user.followings.count %></td>
			<td>フォロワー数:<%= user.followers.count %></td>
			<td><%= render 'relationships/follow_button', user: user %></td>
			<td><%= link_to "Show", user_path(user) %></td>
		</tr>
	</tbody>
	<% end %>
</table>

</div>

app/views/users/followings.html.erb
<div class="container">

<h1>Following Users</h1>

<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th></th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<% @user.followings.each do |user| %>
	<tbody>
		<tr>
			<td><%= attachment_image_tag user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %>
			<td><%= user.name %></td>
			<td>フォロー数:<%= user.followings.count %></td>
			<td>フォロワー数:<%= user.followers.count %></td>
			<td><%= render 'relationships/follow_button', user: user %></td>
			<td><%= link_to "Show", user_path(user) %></td>
		</tr>
	</tbody>
	<% end %>
</table>
</div>

app/views/users/index.html.erb
<div class="container">
	<% if @book.errors.any? %>
		<p><%= @book.errors.count %>error prohibited this obj from being saved: </p>
		<ul>
			<% @book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>

	<div class="row">
		<div class="col-xs-3">
			<h2>User info</h2>
			<%= attachment_image_tag current_user, :profile_image, size: "100x100", format: 'jpeg', fallback: "no_image.jpg" %>
			<table class="table">
				<tbody>
					<tr></tr>
					<tr>
						<th><label>name</label></th>
						<td><%= current_user.name %></td>
					</tr>
					<tr>
						<th><label>introduction</label></th>
						<td><%= current_user.introduction %></td>
					</tr>
					<tr>
						<th><label>follows</label></th>
						<td>
							<a href="<%= followings_user_path(current_user) %>"><%= current_user.followings.count %></a>
						</td>
					</tr>
					<tr>
						<th><label>followers</label></th>
						<td>
							<a href="<%= followers_user_path(current_user) %>"><%= current_user.followers.count %></a>
						</td>
					</tr>
				</tbody>
			</table>
			<div class="row">
				<%= link_to "", edit_user_path(current_user) , class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_18935" %>
			</div>
			<h2>New book</h2>
			<%= form_for(@book) do |f| %>
				<div class="field row">
						<label>Title</label>
						<%= f.text_field :title, class:"col-xs-12 book_title" %>
				</div>
				<div class="field row">
						<label>Opinion</label>
						<%= f.text_area :body, class:"col-xs-12 book_body"%>
				</div>
				<div class="actions row">
					<%= f.submit "Create Book", class:"btn btn-primary col-xs-12" %>
				</div>
			<% end %>
		</div>

		<div class="col-xs-9">
			<h2>Users</h2>
			<table class="table">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th></th>
						<th></th>
						<th></th>
						<th></th>
					</tr>
				</thead>
				<tbody>
				<% @users.each do |user| %>
					<tr>
						<td>
							<%= attachment_image_tag user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %>
						</td>
						<td>
							<%= user.name %>
						</td>
						<td>フォロー数:<%= user.followings.count %></td>
						<td>フォロワー数:<%= user.followers.count %></td>
						<td>
							<%= render 'relationships/follow_button', user: user %>
						</td>
						<td>
							<%= link_to "Show", user_path(user) %>
						</td>
					</tr>
				<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class ="container">
	<div id="error">
		<% if @book.errors.any? %>
			<p><%= @book.errors.count %>error prohibited this obj from being saved: </p>
			<ul>
				<% @book.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		<% end %>
	</div>

	<% if flash[:notice] %>
		<div class="flash notice"><%= flash[:notice] %></div>
	<% end %>


	<div class="row">
		<div class="col-xs-3">
			<h2>User info</h2>
			<div class="user">
				<%= attachment_image_tag @user, :profile_image, size: "100x100", format: 'jpeg', fallback: "no_image.jpg" %>
				<table class="table">
					<tbody>
						<tr></tr>
						<tr>
							<th><label>name</label></th>
							<td><p><%= @user.name %></p></td>
						<tr>
							<th><label>introduction</label></th>
							<td><p><%= @user.introduction %></p></td>
						</tr>
						<tr>
							<th><label>follows</label></th>
							<td><a href="<%= followings_user_path(@user) %>"><%= @user.followings.count %></a></td>
						</tr>
						<tr>
							<th><label>followers</label></th>
							<td><a href="<%= followers_user_path(@user) %>"><%= @user.followers.count %></a></td>
						</tr>
					</tbody>
				</table>
				<div class="row">
					<% if @user.id == current_user.id %>
						<%= link_to "", edit_user_path(@user), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_18898" %>
					<% end %>
				</div>
			</div>

			<div class="create">
				<h2>New book</h2>
				<%= form_for(@book) do |f| %>
					<div class="field row">
						<label>Title</label>
						<%= f.text_field :title , class:"col-xs-12 book_title"%>
					</div>
					<div class="field row">
						<label>Opinion</label>
						<%= f.text_area :body , class:"col-xs-12 book_body"%>
					</div>
					<div class="action row">
					<%= f.submit "Create Book", class:"btn btn-primary col-xs-12" %>
					</div>
				<% end %>
			</div>
		</div>

		<div class="col-xs-9">
			<h2>Books</h2>

			<table class="table table-hover table-inverse">
			  	<thaed>
			  		<tr>
			  		<th></th><th>Title</th><th>Opinion</th><th></th>
			  		</tr>
			  	</thaed>
			  	<% @books.each do |book| %>
			  	<tbody>
			  	<tr>
			  		<td><%= attachment_image_tag book.user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %></td>
			  		<td><%= link_to book_path(book.id) do %>
									<%= book.title %>
								<% end %></td>
			  		<td><%= book.body %></td>
			  	</tr>
			  	</tbody>
			  	<% end %>
			</table>
		</div>
	</div>
</div>